//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mof.open/Messaging/ServiceContracts/1/0/", ConfigurationName="WcfMessagingCallbackService.IMessagingCallback.IMessagingCallback")]
    public interface IMessagingCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mof.open/Messaging/ServiceContracts/1/0/IMessagingCallback/ProcessMessage", ReplyAction="http://mof.open/Messaging/ServiceContracts/1/0/IMessagingCallback/ProcessResponse" +
            "Response")]
        Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse ProcessResponse(Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://mof.open/Messaging/ServiceContracts/1/0/IMessagingCallback/ProcessMessage", ReplyAction="http://mof.open/Messaging/ServiceContracts/1/0/IMessagingCallback/ProcessResponse" +
            "Response")]
        System.IAsyncResult BeginProcessResponse(Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request, System.AsyncCallback callback, object asyncState);
        
        Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse EndProcessResponse(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessResponse", WrapperNamespace="http://mof.open/Messaging/ServiceContracts/1/0/", IsWrapped=true)]
    public partial class ProcessResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mof.open/Messaging/ServiceContracts/1/0/", Order=0)]
        public object message;
        
        public ProcessResponseRequest() {
        }
        
        public ProcessResponseRequest(object message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessResponseResponse", WrapperNamespace="http://mof.open/Messaging/ServiceContracts/1/0/", IsWrapped=true)]
    public partial class ProcessResponseResponse {
        
        public ProcessResponseResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMessagingCallbackChannel : Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.IMessagingCallback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProcessResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProcessResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MessagingCallbackClient : System.ServiceModel.ClientBase<Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.IMessagingCallback>, Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.IMessagingCallback {
        
        private BeginOperationDelegate onBeginProcessResponseDelegate;
        
        private EndOperationDelegate onEndProcessResponseDelegate;
        
        private System.Threading.SendOrPostCallback onProcessResponseCompletedDelegate;
        
        public MessagingCallbackClient() {
        }
        
        public MessagingCallbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingCallbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingCallbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingCallbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ProcessResponseCompletedEventArgs> ProcessResponseCompleted;
        
        public Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse ProcessResponse(Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request) {
            return base.Channel.ProcessResponse(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginProcessResponse(Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProcessResponse(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse EndProcessResponse(System.IAsyncResult result) {
            return base.Channel.EndProcessResponse(result);
        }
        
        private System.IAsyncResult OnBeginProcessResponse(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request = ((Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest)(inValues[0]));
            return this.BeginProcessResponse(request, callback, asyncState);
        }
        
        private object[] OnEndProcessResponse(System.IAsyncResult result) {
            Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseResponse retVal = this.EndProcessResponse(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProcessResponseCompleted(object state) {
            if ((this.ProcessResponseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProcessResponseCompleted(this, new ProcessResponseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProcessResponseAsync(Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request) {
            this.ProcessResponseAsync(request, null);
        }
        
        public void ProcessResponseAsync(Open.MOF.BizTalk.Test.WcfMessagingCallbackService.IMessagingCallback.ProcessResponseRequest request, object userState) {
            if ((this.onBeginProcessResponseDelegate == null)) {
                this.onBeginProcessResponseDelegate = new BeginOperationDelegate(this.OnBeginProcessResponse);
            }
            if ((this.onEndProcessResponseDelegate == null)) {
                this.onEndProcessResponseDelegate = new EndOperationDelegate(this.OnEndProcessResponse);
            }
            if ((this.onProcessResponseCompletedDelegate == null)) {
                this.onProcessResponseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProcessResponseCompleted);
            }
            base.InvokeAsync(this.onBeginProcessResponseDelegate, new object[] {
                        request}, this.onEndProcessResponseDelegate, this.onProcessResponseCompletedDelegate, userState);
        }
    }
}
