//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.ServiceContractAttribute(Namespace = "http://microsoft.practices.esb/", ConfigurationName = "MOF.BizTalkESB.IProcessRequestResponse")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://microsoft.practices.esb/", ConfigurationName = "MOF.BizTalkESB.IProcessRequestResponse", ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
    internal interface IProcessRequestResponse
    {
        
        // CODEGEN: Generating message contract since message SubmitRequestResponse requires protection.
        [System.ServiceModel.OperationContractAttribute(Action="SubmitRequestResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseResponse SubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="SubmitRequestResponse", ReplyAction="*")]
        System.IAsyncResult BeginSubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest request, System.AsyncCallback callback, object asyncState);

        Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseResponse EndSubmitRequestResponse(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ItineraryDescription
    {
        
        private string nameField;
        
        private string versionField;
        
        private string guidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false, ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
    internal partial class SubmitRequestResponseRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.biztalk.practices.esb.com/itinerary", ProtectionLevel=System.Net.Security.ProtectionLevel.None)]
        public Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription;
        
        //[System.ServiceModel.MessageBodyMemberAttribute(Namespace="", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", ProtectionLevel = System.Net.Security.ProtectionLevel.None, Order = 0)]
        public object part;
        
        public SubmitRequestResponseRequest()
        {
        }

        public SubmitRequestResponseRequest(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription, object part)
        {
            this.ItineraryDescription = ItineraryDescription;
            this.part = part;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false, ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
    internal partial class SubmitRequestResponseResponse
    {
        
        //[System.ServiceModel.MessageBodyMemberAttribute(Namespace="", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", ProtectionLevel = System.Net.Security.ProtectionLevel.None, Order = 0)]
        public object part;
        
        public SubmitRequestResponseResponse()
        {
        }
        
        public SubmitRequestResponseResponse(object part)
        {
            this.part = part;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface ProcessRequestResponseChannel : Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal partial class SubmitRequestResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public SubmitRequestResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public object Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal partial class ProcessRequestResponseClient : System.ServiceModel.ClientBase<Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse>, Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse
    {
        
        private BeginOperationDelegate onBeginSubmitRequestResponseDelegate;
        
        private EndOperationDelegate onEndSubmitRequestResponseDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitRequestResponseCompletedDelegate;
        
        public ProcessRequestResponseClient()
        {
        }
        
        public ProcessRequestResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProcessRequestResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProcessRequestResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProcessRequestResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public event System.EventHandler<SubmitRequestResponseCompletedEventArgs> SubmitRequestResponseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseResponse Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse.SubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest request)
        {
            return base.Channel.SubmitRequestResponse(request);
        }

        public void SubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription, ref object part)
        {
            Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest inValue = new Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest();
            inValue.ItineraryDescription = ItineraryDescription;
            inValue.part = part;
            Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseResponse retVal = ((Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse)(this)).SubmitRequestResponse(inValue);
            part = retVal.part;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse.BeginSubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSubmitRequestResponse(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription, object part, System.AsyncCallback callback, object asyncState)
        {
            Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest inValue = new Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseRequest();
            inValue.ItineraryDescription = ItineraryDescription;
            inValue.part = part;
            return ((Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse)(this)).BeginSubmitRequestResponse(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseResponse Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse.EndSubmitRequestResponse(System.IAsyncResult result)
        {
            return base.Channel.EndSubmitRequestResponse(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public object EndSubmitRequestResponse(System.IAsyncResult result)
        {
            Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.SubmitRequestResponseResponse retVal = ((Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.IProcessRequestResponse)(this)).EndSubmitRequestResponse(result);
            return retVal.part;
        }
        
        private System.IAsyncResult OnBeginSubmitRequestResponse(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription = ((Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription)(inValues[0]));
            object part = ((object)(inValues[1]));
            return this.BeginSubmitRequestResponse(ItineraryDescription, part, callback, asyncState);
        }
        
        private object[] OnEndSubmitRequestResponse(System.IAsyncResult result)
        {
            object retVal = this.EndSubmitRequestResponse(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitRequestResponseCompleted(object state)
        {
            if ((this.SubmitRequestResponseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitRequestResponseCompleted(this, new SubmitRequestResponseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void SubmitRequestResponseAsync(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription, object part)
        {
            this.SubmitRequestResponseAsync(ItineraryDescription, part, null);
        }

        public void SubmitRequestResponseAsync(Open.MOF.BizTalk.Adapters.Proxy.ItineraryTwoWayServiceInstance.ItineraryDescription ItineraryDescription, object part, object userState)
        {
            if ((this.onBeginSubmitRequestResponseDelegate == null))
            {
                this.onBeginSubmitRequestResponseDelegate = new BeginOperationDelegate(this.OnBeginSubmitRequestResponse);
            }
            if ((this.onEndSubmitRequestResponseDelegate == null))
            {
                this.onEndSubmitRequestResponseDelegate = new EndOperationDelegate(this.OnEndSubmitRequestResponse);
            }
            if ((this.onSubmitRequestResponseCompletedDelegate == null))
            {
                this.onSubmitRequestResponseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitRequestResponseCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitRequestResponseDelegate, new object[] {
                        ItineraryDescription,
                        part}, this.onEndSubmitRequestResponseDelegate, this.onSubmitRequestResponseCompletedDelegate, userState);
        }
    }
}
