//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Open.MOF.BizTalk.Services.Proxy
{



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://safety-kleen.org/SubscriptionManagement/ServiceContracts/1/0/", ConfigurationName = "WcfService_OrchestrationProject")]
    public interface WcfService_OrchestrationProject
    {

        // CODEGEN: Generating message contract since the operation ProcessSubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessSubscribe", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ProcessSubscribeResponse ProcessSubscribe(ProcessSubscribeRequest request);

        // CODEGEN: Generating message contract since the operation ProcessUnsubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessUnsubscribe", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ProcessUnsubscribeResponse ProcessUnsubscribe(ProcessUnsubscribeRequest request);
    }

    // duplicated for queued messaging
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://safety-kleen.org/SubscriptionManagement/ServiceContracts/1/0/", ConfigurationName = "WcfService_OrchestrationProjectOneWay")]
    public interface WcfService_OrchestrationProjectOneWay
    {

        // CODEGEN: Generating message contract since the operation ProcessSubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessSubscribe", IsOneWay = true)]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ProcessSubscribe(ProcessSubscribeRequest request);

        // CODEGEN: Generating message contract since the operation ProcessUnsubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessUnsubscribe", IsOneWay = true)]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ProcessUnsubscribe(ProcessUnsubscribeRequest request);
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/")]
    public partial class SubscribeRequestMessage
    {

        private string messageIdField;

        private string toField;

        private string fromField;

        private string relatesToField;

        private string replyToField;

        private string messageXmlTypeField;

        private string endpointUriField;

        private string actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string relatesTo
        {
            get
            {
                return this.relatesToField;
            }
            set
            {
                this.relatesToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string replyTo
        {
            get
            {
                return this.replyToField;
            }
            set
            {
                this.replyToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string messageXmlType
        {
            get
            {
                return this.messageXmlTypeField;
            }
            set
            {
                this.messageXmlTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string endpointUri
        {
            get
            {
                return this.endpointUriField;
            }
            set
            {
                this.endpointUriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessSubscribeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/", Order = 0)]
        public SubscribeRequestMessage SubscribeRequestMessage;

        public ProcessSubscribeRequest()
        {
        }

        public ProcessSubscribeRequest(SubscribeRequestMessage SubscribeRequestMessage)
        {
            this.SubscribeRequestMessage = SubscribeRequestMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessSubscribeResponse
    {

        public ProcessSubscribeResponse()
        {
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/")]
    public partial class UnsubscribeRequestMessage
    {

        private string messageIdField;

        private string toField;

        private string fromField;

        private string relatesToField;

        private string replyToField;

        private string messageXmlTypeField;

        private string endpointUriField;

        private string actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string relatesTo
        {
            get
            {
                return this.relatesToField;
            }
            set
            {
                this.relatesToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string replyTo
        {
            get
            {
                return this.replyToField;
            }
            set
            {
                this.replyToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string messageXmlType
        {
            get
            {
                return this.messageXmlTypeField;
            }
            set
            {
                this.messageXmlTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string endpointUri
        {
            get
            {
                return this.endpointUriField;
            }
            set
            {
                this.endpointUriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessUnsubscribeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/", Order = 0)]
        public UnsubscribeRequestMessage UnsubscribeRequestMessage;

        public ProcessUnsubscribeRequest()
        {
        }

        public ProcessUnsubscribeRequest(UnsubscribeRequestMessage UnsubscribeRequestMessage)
        {
            this.UnsubscribeRequestMessage = UnsubscribeRequestMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessUnsubscribeResponse
    {

        public ProcessUnsubscribeResponse()
        {
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WcfService_OrchestrationProjectChannel : WcfService_OrchestrationProject, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WcfService_OrchestrationProjectClient : System.ServiceModel.ClientBase<WcfService_OrchestrationProject>, WcfService_OrchestrationProject
    {

        public WcfService_OrchestrationProjectClient()
        {
        }

        public WcfService_OrchestrationProjectClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        public WcfService_OrchestrationProjectClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WcfService_OrchestrationProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WcfService_OrchestrationProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcessSubscribeResponse WcfService_OrchestrationProject.ProcessSubscribe(ProcessSubscribeRequest request)
        {
            return base.Channel.ProcessSubscribe(request);
        }

        public void ProcessSubscribe(SubscribeRequestMessage SubscribeRequestMessage)
        {
            ProcessSubscribeRequest inValue = new ProcessSubscribeRequest();
            inValue.SubscribeRequestMessage = SubscribeRequestMessage;
            ProcessSubscribeResponse retVal = ((WcfService_OrchestrationProject)(this)).ProcessSubscribe(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcessUnsubscribeResponse WcfService_OrchestrationProject.ProcessUnsubscribe(ProcessUnsubscribeRequest request)
        {
            return base.Channel.ProcessUnsubscribe(request);
        }

        public void ProcessUnsubscribe(UnsubscribeRequestMessage UnsubscribeRequestMessage)
        {
            ProcessUnsubscribeRequest inValue = new ProcessUnsubscribeRequest();
            inValue.UnsubscribeRequestMessage = UnsubscribeRequestMessage;
            ProcessUnsubscribeResponse retVal = ((WcfService_OrchestrationProject)(this)).ProcessUnsubscribe(inValue);
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WcfService_OrchestrationProjectOneWayClient : System.ServiceModel.ClientBase<WcfService_OrchestrationProjectOneWay>, WcfService_OrchestrationProjectOneWay
    {

        public WcfService_OrchestrationProjectOneWayClient()
        {
        }

        public WcfService_OrchestrationProjectOneWayClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        public WcfService_OrchestrationProjectOneWayClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WcfService_OrchestrationProjectOneWayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WcfService_OrchestrationProjectOneWayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WcfService_OrchestrationProjectOneWay.ProcessSubscribe(ProcessSubscribeRequest request)
        {
            base.Channel.ProcessSubscribe(request);
        }

        public void ProcessSubscribe(SubscribeRequestMessage SubscribeRequestMessage)
        {
            ProcessSubscribeRequest inValue = new ProcessSubscribeRequest();
            inValue.SubscribeRequestMessage = SubscribeRequestMessage;
            ((WcfService_OrchestrationProjectOneWay)(this)).ProcessSubscribe(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WcfService_OrchestrationProjectOneWay.ProcessUnsubscribe(ProcessUnsubscribeRequest request)
        {
            base.Channel.ProcessUnsubscribe(request);
        }

        public void ProcessUnsubscribe(UnsubscribeRequestMessage UnsubscribeRequestMessage)
        {
            ProcessUnsubscribeRequest inValue = new ProcessUnsubscribeRequest();
            inValue.UnsubscribeRequestMessage = UnsubscribeRequestMessage;
            ((WcfService_OrchestrationProjectOneWay)(this)).ProcessUnsubscribe(inValue);
        }
    }

}