//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Open.MOF.BizTalk.Services.Proxy.EsbSubscriptionManagementInstance
{



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://safety-kleen.org/SubscriptionManagement/ServiceContracts/1/0/", ConfigurationName = "Open.MOF.BizTalk.Services.Proxy.EsbSubscriptionManagementInstance.SubscriptionManagement")]
    public interface SubscriptionManagement
    {

        // CODEGEN: Generating message contract since the operation ProcessSubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessSubscribe", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ProcessSubscribeResponse ProcessSubscribe(ProcessSubscribeRequest request);

        // CODEGEN: Generating message contract since the operation ProcessUnsubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessUnsubscribe", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ProcessUnsubscribeResponse ProcessUnsubscribe(ProcessUnsubscribeRequest request);
    }

    // duplicated for queued messaging
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://safety-kleen.org/SubscriptionManagement/ServiceContracts/1/0/", ConfigurationName = "Open.MOF.BizTalk.Services.Proxy.EsbSubscriptionManagementInstance.SubscriptionManagementQueued")]
    public interface SubscriptionManagementQueued
    {

        // CODEGEN: Generating message contract since the operation ProcessSubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessSubscribe", IsOneWay = true)]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ProcessSubscribe(ProcessSubscribeRequest request);

        // CODEGEN: Generating message contract since the operation ProcessUnsubscribe is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "ProcessUnsubscribe", IsOneWay = true)]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ProcessUnsubscribe(ProcessUnsubscribeRequest request);
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/")]
    public partial class SubscribeRequestMessage
    {

        private string messageIdField;

        private string toField;

        private string fromField;

        private string relatesToField;

        private string replyToField;

        private string messageXmlTypeField;

        private string endpointUriField;

        private string actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string relatesTo
        {
            get
            {
                return this.relatesToField;
            }
            set
            {
                this.relatesToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string replyTo
        {
            get
            {
                return this.replyToField;
            }
            set
            {
                this.replyToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string messageXmlType
        {
            get
            {
                return this.messageXmlTypeField;
            }
            set
            {
                this.messageXmlTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string endpointUri
        {
            get
            {
                return this.endpointUriField;
            }
            set
            {
                this.endpointUriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessSubscribeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/", Order = 0)]
        public SubscribeRequestMessage SubscribeRequestMessage;

        public ProcessSubscribeRequest()
        {
        }

        public ProcessSubscribeRequest(SubscribeRequestMessage SubscribeRequestMessage)
        {
            this.SubscribeRequestMessage = SubscribeRequestMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessSubscribeResponse
    {

        public ProcessSubscribeResponse()
        {
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/")]
    public partial class UnsubscribeRequestMessage
    {

        private string messageIdField;

        private string toField;

        private string fromField;

        private string relatesToField;

        private string replyToField;

        private string messageXmlTypeField;

        private string endpointUriField;

        private string actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string relatesTo
        {
            get
            {
                return this.relatesToField;
            }
            set
            {
                this.relatesToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string replyTo
        {
            get
            {
                return this.replyToField;
            }
            set
            {
                this.replyToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string messageXmlType
        {
            get
            {
                return this.messageXmlTypeField;
            }
            set
            {
                this.messageXmlTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string endpointUri
        {
            get
            {
                return this.endpointUriField;
            }
            set
            {
                this.endpointUriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessUnsubscribeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://safety-kleen.com/SubscriptionManagement/ServiceContracts/1/0/", Order = 0)]
        public UnsubscribeRequestMessage UnsubscribeRequestMessage;

        public ProcessUnsubscribeRequest()
        {
        }

        public ProcessUnsubscribeRequest(UnsubscribeRequestMessage UnsubscribeRequestMessage)
        {
            this.UnsubscribeRequestMessage = UnsubscribeRequestMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ProcessUnsubscribeResponse
    {

        public ProcessUnsubscribeResponse()
        {
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SubscriptionManagementChannel : SubscriptionManagement, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SubscriptionManagementClient : System.ServiceModel.ClientBase<SubscriptionManagement>, SubscriptionManagement
    {

        public SubscriptionManagementClient()
        {
        }

        public SubscriptionManagementClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        public SubscriptionManagementClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SubscriptionManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SubscriptionManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcessSubscribeResponse SubscriptionManagement.ProcessSubscribe(ProcessSubscribeRequest request)
        {
            return base.Channel.ProcessSubscribe(request);
        }

        public void ProcessSubscribe(SubscribeRequestMessage SubscribeRequestMessage)
        {
            ProcessSubscribeRequest inValue = new ProcessSubscribeRequest();
            inValue.SubscribeRequestMessage = SubscribeRequestMessage;
            ProcessSubscribeResponse retVal = ((SubscriptionManagement)(this)).ProcessSubscribe(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcessUnsubscribeResponse SubscriptionManagement.ProcessUnsubscribe(ProcessUnsubscribeRequest request)
        {
            return base.Channel.ProcessUnsubscribe(request);
        }

        public void ProcessUnsubscribe(UnsubscribeRequestMessage UnsubscribeRequestMessage)
        {
            ProcessUnsubscribeRequest inValue = new ProcessUnsubscribeRequest();
            inValue.UnsubscribeRequestMessage = UnsubscribeRequestMessage;
            ProcessUnsubscribeResponse retVal = ((SubscriptionManagement)(this)).ProcessUnsubscribe(inValue);
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SubscriptionManagementQueuedClient : System.ServiceModel.ClientBase<SubscriptionManagementQueued>, SubscriptionManagementQueued
    {

        public SubscriptionManagementQueuedClient()
        {
        }

        public SubscriptionManagementQueuedClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        public SubscriptionManagementQueuedClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SubscriptionManagementQueuedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SubscriptionManagementQueuedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SubscriptionManagementQueued.ProcessSubscribe(ProcessSubscribeRequest request)
        {
            base.Channel.ProcessSubscribe(request);
        }

        public void ProcessSubscribe(SubscribeRequestMessage SubscribeRequestMessage)
        {
            ProcessSubscribeRequest inValue = new ProcessSubscribeRequest();
            inValue.SubscribeRequestMessage = SubscribeRequestMessage;
            ((SubscriptionManagementQueued)(this)).ProcessSubscribe(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SubscriptionManagementQueued.ProcessUnsubscribe(ProcessUnsubscribeRequest request)
        {
            base.Channel.ProcessUnsubscribe(request);
        }

        public void ProcessUnsubscribe(UnsubscribeRequestMessage UnsubscribeRequestMessage)
        {
            ProcessUnsubscribeRequest inValue = new ProcessUnsubscribeRequest();
            inValue.UnsubscribeRequestMessage = UnsubscribeRequestMessage;
            ((SubscriptionManagementQueued)(this)).ProcessUnsubscribe(inValue);
        }
    }

}