//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //[System.ServiceModel.ServiceContractAttribute(Namespace = "http://microsoft.practices.esb", ConfigurationName = "MOF.BizTalkESB.IProcessSoap")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://microsoft.practices.esb", ConfigurationName = "MOF.BizTalkESB.IProcessSoap", ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
    public interface IProcessSoap
    {

        // CODEGEN: Generating message contract since message SubmitRequestResponseRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action = "http://microsoft.practices.esb/Process/SubmitRequestResponse", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseResponse SubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://microsoft.practices.esb/Process/SubmitRequestResponse", ReplyAction = "*")]
        System.IAsyncResult BeginSubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest request, System.AsyncCallback callback, object asyncState);

        Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseResponse EndSubmitRequestResponse(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class Itinerary : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ItineraryBizTalkSegment bizTalkSegmentField;

        private ItineraryServiceInstance serviceInstanceField;

        private ItineraryServices[] servicesField;

        private ArrayOfItineraryResolversResolvers[] resolverGroupsField;

        private ArrayOfItineraryPropertyProperty[] propertyBagField;

        private string uuidField;

        private string beginTimeField;

        private string completeTimeField;

        private string stateField;

        private bool isRequestResponseField;

        private bool isRequestResponseFieldSpecified;

        private int servicecountField;

        private string nameField;

        private string versionField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ItineraryBizTalkSegment BizTalkSegment
        {
            get
            {
                return this.bizTalkSegmentField;
            }
            set
            {
                this.bizTalkSegmentField = value;
                this.RaisePropertyChanged("BizTalkSegment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ItineraryServiceInstance ServiceInstance
        {
            get
            {
                return this.serviceInstanceField;
            }
            set
            {
                this.serviceInstanceField = value;
                this.RaisePropertyChanged("ServiceInstance");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Services", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public ItineraryServices[] Services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
                this.RaisePropertyChanged("Services");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resolvers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ArrayOfItineraryResolversResolvers[] ResolverGroups
        {
            get
            {
                return this.resolverGroupsField;
            }
            set
            {
                this.resolverGroupsField = value;
                this.RaisePropertyChanged("ResolverGroups");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ArrayOfItineraryPropertyProperty[] PropertyBag
        {
            get
            {
                return this.propertyBagField;
            }
            set
            {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string beginTime
        {
            get
            {
                return this.beginTimeField;
            }
            set
            {
                this.beginTimeField = value;
                this.RaisePropertyChanged("beginTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string completeTime
        {
            get
            {
                return this.completeTimeField;
            }
            set
            {
                this.completeTimeField = value;
                this.RaisePropertyChanged("completeTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRequestResponse
        {
            get
            {
                return this.isRequestResponseField;
            }
            set
            {
                this.isRequestResponseField = value;
                this.RaisePropertyChanged("isRequestResponse");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isRequestResponseSpecified
        {
            get
            {
                return this.isRequestResponseFieldSpecified;
            }
            set
            {
                this.isRequestResponseFieldSpecified = value;
                this.RaisePropertyChanged("isRequestResponseSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int servicecount
        {
            get
            {
                return this.servicecountField;
            }
            set
            {
                this.servicecountField = value;
                this.RaisePropertyChanged("servicecount");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ItineraryBizTalkSegment : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string interchangeIdField;

        private string epmRRCorrelationTokenField;

        private string receiveInstanceIdField;

        private string messageIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string interchangeId
        {
            get
            {
                return this.interchangeIdField;
            }
            set
            {
                this.interchangeIdField = value;
                this.RaisePropertyChanged("interchangeId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string epmRRCorrelationToken
        {
            get
            {
                return this.epmRRCorrelationTokenField;
            }
            set
            {
                this.epmRRCorrelationTokenField = value;
                this.RaisePropertyChanged("epmRRCorrelationToken");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string receiveInstanceId
        {
            get
            {
                return this.receiveInstanceIdField;
            }
            set
            {
                this.receiveInstanceIdField = value;
                this.RaisePropertyChanged("receiveInstanceId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ItineraryServiceInstance : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string uuidField;

        private string nameField;

        private string typeField;

        private string stateField;

        private int positionField;

        private bool positionFieldSpecified;

        private bool isRequestResponseField;

        private bool isRequestResponseFieldSpecified;

        private Stages stageField;

        private bool stageFieldSpecified;

        private string idField;

        private string nextIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
                this.RaisePropertyChanged("positionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRequestResponse
        {
            get
            {
                return this.isRequestResponseField;
            }
            set
            {
                this.isRequestResponseField = value;
                this.RaisePropertyChanged("isRequestResponse");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isRequestResponseSpecified
        {
            get
            {
                return this.isRequestResponseFieldSpecified;
            }
            set
            {
                this.isRequestResponseFieldSpecified = value;
                this.RaisePropertyChanged("isRequestResponseSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Stages stage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
                this.RaisePropertyChanged("stage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stageSpecified
        {
            get
            {
                return this.stageFieldSpecified;
            }
            set
            {
                this.stageFieldSpecified = value;
                this.RaisePropertyChanged("stageSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get
            {
                return this.nextIdField;
            }
            set
            {
                this.nextIdField = value;
                this.RaisePropertyChanged("nextId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public enum Stages
    {

        /// <remarks/>
        notSpecified,

        /// <remarks/>
        receiveInbound,

        /// <remarks/>
        receiveTransmit,

        /// <remarks/>
        sendTransmit,

        /// <remarks/>
        sendInbound,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ItineraryServices : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ItineraryServicesService serviceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ItineraryServicesService Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ItineraryServicesService : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ArrayOfItineraryServicesServicePropertyProperty[] propertyBagField;

        private string uuidField;

        private string beginTimeField;

        private string completeTimeField;

        private string nameField;

        private string typeField;

        private string stateField;

        private bool resolveField;

        private bool resolveFieldSpecified;

        private bool isRequestResponseField;

        private bool isRequestResponseFieldSpecified;

        private int positionField;

        private bool positionFieldSpecified;

        private string serviceInstanceIdField;

        private bool isTrackingEnabledField;

        private bool isTrackingEnabledFieldSpecified;

        private Stages stageField;

        private bool stageFieldSpecified;

        private string idField;

        private string nextIdField;

        private string businessNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ArrayOfItineraryServicesServicePropertyProperty[] PropertyBag
        {
            get
            {
                return this.propertyBagField;
            }
            set
            {
                this.propertyBagField = value;
                this.RaisePropertyChanged("PropertyBag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string beginTime
        {
            get
            {
                return this.beginTimeField;
            }
            set
            {
                this.beginTimeField = value;
                this.RaisePropertyChanged("beginTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string completeTime
        {
            get
            {
                return this.completeTimeField;
            }
            set
            {
                this.completeTimeField = value;
                this.RaisePropertyChanged("completeTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool resolve
        {
            get
            {
                return this.resolveField;
            }
            set
            {
                this.resolveField = value;
                this.RaisePropertyChanged("resolve");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resolveSpecified
        {
            get
            {
                return this.resolveFieldSpecified;
            }
            set
            {
                this.resolveFieldSpecified = value;
                this.RaisePropertyChanged("resolveSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRequestResponse
        {
            get
            {
                return this.isRequestResponseField;
            }
            set
            {
                this.isRequestResponseField = value;
                this.RaisePropertyChanged("isRequestResponse");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isRequestResponseSpecified
        {
            get
            {
                return this.isRequestResponseFieldSpecified;
            }
            set
            {
                this.isRequestResponseFieldSpecified = value;
                this.RaisePropertyChanged("isRequestResponseSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
                this.RaisePropertyChanged("positionSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceInstanceId
        {
            get
            {
                return this.serviceInstanceIdField;
            }
            set
            {
                this.serviceInstanceIdField = value;
                this.RaisePropertyChanged("serviceInstanceId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isTrackingEnabled
        {
            get
            {
                return this.isTrackingEnabledField;
            }
            set
            {
                this.isTrackingEnabledField = value;
                this.RaisePropertyChanged("isTrackingEnabled");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTrackingEnabledSpecified
        {
            get
            {
                return this.isTrackingEnabledFieldSpecified;
            }
            set
            {
                this.isTrackingEnabledFieldSpecified = value;
                this.RaisePropertyChanged("isTrackingEnabledSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Stages stage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
                this.RaisePropertyChanged("stage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stageSpecified
        {
            get
            {
                return this.stageFieldSpecified;
            }
            set
            {
                this.stageFieldSpecified = value;
                this.RaisePropertyChanged("stageSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get
            {
                return this.nextIdField;
            }
            set
            {
                this.nextIdField = value;
                this.RaisePropertyChanged("nextId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string businessName
        {
            get
            {
                return this.businessNameField;
            }
            set
            {
                this.businessNameField = value;
                this.RaisePropertyChanged("businessName");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ArrayOfItineraryServicesServicePropertyProperty : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ArrayOfItineraryResolversResolvers : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string serviceIdField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
    public partial class ArrayOfItineraryPropertyProperty : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //[System.ServiceModel.MessageContractAttribute(WrapperName = "SubmitRequestResponse", WrapperNamespace = "http://microsoft.practices.esb", IsWrapped = true)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SubmitRequestResponse", WrapperNamespace = "http://microsoft.practices.esb", IsWrapped = true, ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
    public partial class SubmitRequestResponseRequest
    {

        //[System.ServiceModel.MessageHeaderAttribute(Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary")]
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/itinerary", ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
        public Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary;

        //[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://schemas.microsoft.com/BizTalk/2003/Any", Order = 0)]
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://schemas.microsoft.com/BizTalk/2003/Any", Order = 0, ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
        public System.Xml.XmlNode Root;

        public SubmitRequestResponseRequest()
        {
        }

        public SubmitRequestResponseRequest(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary, System.Xml.XmlNode Root)
        {
            this.Itinerary = Itinerary;
            this.Root = Root;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //[System.ServiceModel.MessageContractAttribute(WrapperName = "SubmitRequestResponseResponse", WrapperNamespace = "http://microsoft.practices.esb", IsWrapped = true)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SubmitRequestResponseResponse", WrapperNamespace = "http://microsoft.practices.esb", IsWrapped = true, ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
    public partial class SubmitRequestResponseResponse
    {

        //[System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://schemas.microsoft.com/BizTalk/2003/Any", Order = 0)]
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://schemas.microsoft.com/BizTalk/2003/Any", Order = 0, ProtectionLevel = System.Net.Security.ProtectionLevel.None)]
        public System.Xml.XmlNode Root;

        public SubmitRequestResponseResponse()
        {
        }

        public SubmitRequestResponseResponse(System.Xml.XmlNode Root)
        {
            this.Root = Root;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessSoapChannel : Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitRequestResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public SubmitRequestResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public System.Xml.XmlNode Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessSoapClient : System.ServiceModel.ClientBase<Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap>, Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap
    {

        private BeginOperationDelegate onBeginSubmitRequestResponseDelegate;

        private EndOperationDelegate onEndSubmitRequestResponseDelegate;

        private System.Threading.SendOrPostCallback onSubmitRequestResponseCompletedDelegate;

        public ProcessSoapClient()
        {
        }

        public ProcessSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ProcessSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ProcessSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ProcessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public event System.EventHandler<SubmitRequestResponseCompletedEventArgs> SubmitRequestResponseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseResponse Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap.SubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest request)
        {
            return base.Channel.SubmitRequestResponse(request);
        }

        public void SubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary, ref System.Xml.XmlNode Root)
        {
            Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest inValue = new Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest();
            inValue.Itinerary = Itinerary;
            inValue.Root = Root;
            Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseResponse retVal = ((Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap)(this)).SubmitRequestResponse(inValue);
            Root = retVal.Root;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap.BeginSubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSubmitRequestResponse(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSubmitRequestResponse(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary, System.Xml.XmlNode Root, System.AsyncCallback callback, object asyncState)
        {
            Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest inValue = new Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseRequest();
            inValue.Itinerary = Itinerary;
            inValue.Root = Root;
            return ((Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap)(this)).BeginSubmitRequestResponse(inValue, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseResponse Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap.EndSubmitRequestResponse(System.IAsyncResult result)
        {
            return base.Channel.EndSubmitRequestResponse(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Xml.XmlNode EndSubmitRequestResponse(System.IAsyncResult result)
        {
            Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.SubmitRequestResponseResponse retVal = ((Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.IProcessSoap)(this)).EndSubmitRequestResponse(result);
            return retVal.Root;
        }

        private System.IAsyncResult OnBeginSubmitRequestResponse(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary = ((Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary)(inValues[0]));
            System.Xml.XmlNode Root = ((System.Xml.XmlNode)(inValues[1]));
            return this.BeginSubmitRequestResponse(Itinerary, Root, callback, asyncState);
        }

        private object[] OnEndSubmitRequestResponse(System.IAsyncResult result)
        {
            System.Xml.XmlNode retVal = this.EndSubmitRequestResponse(result);
            return new object[] {
                    retVal};
        }

        private void OnSubmitRequestResponseCompleted(object state)
        {
            if ((this.SubmitRequestResponseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitRequestResponseCompleted(this, new SubmitRequestResponseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void SubmitRequestResponseAsync(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary, System.Xml.XmlNode Root)
        {
            this.SubmitRequestResponseAsync(Itinerary, Root, null);
        }

        public void SubmitRequestResponseAsync(Open.MOF.BizTalk.Adapters.Proxy.EsbTwoWaySoapInstance.Itinerary Itinerary, System.Xml.XmlNode Root, object userState)
        {
            if ((this.onBeginSubmitRequestResponseDelegate == null))
            {
                this.onBeginSubmitRequestResponseDelegate = new BeginOperationDelegate(this.OnBeginSubmitRequestResponse);
            }
            if ((this.onEndSubmitRequestResponseDelegate == null))
            {
                this.onEndSubmitRequestResponseDelegate = new EndOperationDelegate(this.OnEndSubmitRequestResponse);
            }
            if ((this.onSubmitRequestResponseCompletedDelegate == null))
            {
                this.onSubmitRequestResponseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitRequestResponseCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitRequestResponseDelegate, new object[] {
                        Itinerary,
                        Root}, this.onEndSubmitRequestResponseDelegate, this.onSubmitRequestResponseCompletedDelegate, userState);
        }
    }
}
